In [1]:
'''
作者：英俊
QQ:2227495940
邮箱 同上
'''

'\n作者：英俊\nQQ:2227495940\n邮箱 同上\n'

In [2]:
import pandas as pd
df_train=pd.read_csv(r'C:\Users\Administrator\.fastNLP\dataset\WeiboSenti100k\train.tsv', sep='\t')
df_train.head()

label                                               text
0      0  六一出生的？好讽刺…… //@祭春姬:他爸爸是外星人吧 //@面孔小高:现在的孩子都怎么了 ...
1      1  听过一场！笑死了昂，一听茄子脱口秀，从此节操是路人！[嘻嘻] //@中国梦网官微:@Penc...
2      0             说不出话来[泪] //@央广郭亮：//@戴围脖的Luc:试运营不能搭载乘客的
3      0  疼死我了，一下汗就出来了！扎我一针居然说血不够！原伤口又狠狠的给了一下！十指连心呢！我恨这个...
4      0  凭啥不让发?!支持! //@臭丫头妈:协警叔叔过来挑理，不让发宣传单页。姐只好不发了。结果周...

In [3]:
import pandas as pd
df_dev=pd.read_csv(r'C:\Users\Administrator\.fastNLP\dataset\WeiboSenti100k\dev.tsv', sep='\t')
df_dev.head()

label                                               text
0      0                                     买灯难，难于上青天。[悲伤]
1      1                     @马勒别墅 给新人送上深深的祝福 要幸福哦~ Mia[可爱]
2      1                                      //@广播:[赞][哈哈]
3      0  #快讯#【高速交通广播 广西田东面包车翻下山崖，1死3伤】今天中午，一辆载有5人的面包车，在...
4      1                                  三毛先生你说的好有道理耶！[鼓掌]

In [4]:
import pandas as pd
df_test=pd.read_csv(r'C:\Users\Administrator\.fastNLP\dataset\WeiboSenti100k\test.tsv', sep='\t')
df_test.head()

label                                               text
0      0  就是累了，比舒小姐要早就想离开。[可爱] //@任卫新:受到舒淇影响了[泪]//@赖宝: 生...
1      0                      今天紫外线强度太强了，大家出门注意防晒，[泪][泪][泪]
2      0  ~~ //@lichgo://@雪虹坚持跳绳:小智~~！！ //@Yi淳爱动画:[嘻嘻] 小...
3      0  有一个小姑娘，她有两部ipad，担心我买她的ipad，就把一部送人了，就这样还不放心，情急之...
4      0                                           感动[泪][泪]

In [5]:
df_train['label'].unique()

array([0, 1], dtype=int64)

In [6]:
df_dev['label'].unique()

array([0, 1], dtype=int64)

In [7]:
df_test['label'].unique()

array([0, 1], dtype=int64)

In [8]:
df_train.isnull()

label   text
0      False  False
1      False  False
2      False  False
3      False  False
4      False  False
5      False  False
6      False  False
7      False  False
8      False  False
9      False  False
10     False  False
11     False  False
12     False  False
13     False  False
14     False  False
15     False  False
16     False  False
17     False  False
18     False  False
19     False  False
20     False  False
21     False  False
22     False  False
23     False  False
24     False  False
25     False  False
26     False  False
27     False  False
28     False  False
29     False  False
...      ...    ...
99958  False  False
99959  False  False
99960  False  False
99961  False  False
99962  False  False
99963  False  False
99964  False  False
99965  False  False
99966  False  False
99967  False  False
99968  False  False
99969  False  False
99970  False  False
99971  False  False
99972  False  False
99973  False  False
99974  False  False
99975  False  False
99976  False  False
99977  False  False
99978  False  False
99979  False  False
99980  False  False
99981  False  False
99982  False  False
99983  False  False
99984  False  False
99985  False  False
99986  False  False
99987  False  False

[99988 rows x 2 columns]

In [9]:
df_all=pd.concat([df_train,df_test],ignore_index=True)
df_all.head()

label                                               text
0      0  六一出生的？好讽刺…… //@祭春姬:他爸爸是外星人吧 //@面孔小高:现在的孩子都怎么了 ...
1      1  听过一场！笑死了昂，一听茄子脱口秀，从此节操是路人！[嘻嘻] //@中国梦网官微:@Penc...
2      0             说不出话来[泪] //@央广郭亮：//@戴围脖的Luc:试运营不能搭载乘客的
3      0  疼死我了，一下汗就出来了！扎我一针居然说血不够！原伤口又狠狠的给了一下！十指连心呢！我恨这个...
4      0  凭啥不让发?!支持! //@臭丫头妈:协警叔叔过来挑理，不让发宣传单页。姐只好不发了。结果周...

In [10]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109988 entries, 0 to 109987
Data columns (total 2 columns):
label    109988 non-null int64
text     109988 non-null object
dtypes: int64(1), object(1)
memory usage: 1.7+ MB


In [11]:
df_all['label'].unique()

array([0, 1], dtype=int64)

In [12]:
df_all1=pd.DataFrame({"raw_words":df_all['text'],"target":df_all['label']})

In [13]:
df_all1.to_csv('df_train.txt',sep='\t', index=False,header=None,encoding='utf-8')

In [14]:
df_all1.head()

raw_words  target
0  六一出生的？好讽刺…… //@祭春姬:他爸爸是外星人吧 //@面孔小高:现在的孩子都怎么了 ...       0
1  听过一场！笑死了昂，一听茄子脱口秀，从此节操是路人！[嘻嘻] //@中国梦网官微:@Penc...       1
2             说不出话来[泪] //@央广郭亮：//@戴围脖的Luc:试运营不能搭载乘客的       0
3  疼死我了，一下汗就出来了！扎我一针居然说血不够！原伤口又狠狠的给了一下！十指连心呢！我恨这个...       0
4  凭啥不让发?!支持! //@臭丫头妈:协警叔叔过来挑理，不让发宣传单页。姐只好不发了。结果周...       0

In [15]:
df_dev['label'].unique()

array([0, 1], dtype=int64)

In [17]:
# testlist=df_test['label']
# # trainlist=int(trainlist)
# testlist=[int(i) for i in testlist]
# ,'target':df_test['label']
df_test1=pd.DataFrame({'raw_words':df_test['text']})
df_test1.head()


raw_words
0  就是累了，比舒小姐要早就想离开。[可爱] //@任卫新:受到舒淇影响了[泪]//@赖宝: 生...
1                      今天紫外线强度太强了，大家出门注意防晒，[泪][泪][泪]
2  ~~ //@lichgo://@雪虹坚持跳绳:小智~~！！ //@Yi淳爱动画:[嘻嘻] 小...
3  有一个小姑娘，她有两部ipad，担心我买她的ipad，就把一部送人了，就这样还不放心，情急之...
4                                           感动[泪][泪]

In [18]:
df_test1.to_csv('df_test.txt',sep='\t', index=False,header=None,encoding='utf-8')

# 数据导入

In [19]:
#导入Pytorch包

import torch

import torch.nn as nn

from fastNLP.io.loader import CSVLoader

dataset_loader = CSVLoader(headers=('raw_words','target'), sep='\t')
testset_loader = CSVLoader( headers=['raw_words'],sep='\t')

In [20]:
# 表示将CSV文件中每一行的第一项将填入'raw_words' field，第二项填入'target' field。

# 其中项之间由'\t'分割开来

train_path=r'df_train.txt'

test_path=r'df_test.txt'

dataset = dataset_loader._load(train_path)

testset = testset_loader._load(test_path)

In [21]:
# 将句子分成单词形式, 详见DataSet.apply()方法

import jieba

from itertools import chain

print(jieba.__version__)
# from itertools import chain

#     '''

#     @params:

#         data: 数据的列表，列表中的每个元素为 [文本字符串，0/1标签] 二元组

#     @return: 切分词后的文本的列表，列表中的每个元素为切分后的词序列

#     '''

def get_tokenized(data,words=True):
    def tokenizer(text):
        return [tok for tok in jieba.cut(text, cut_all=False)]
    if words:

        #按词语进行编码

        return tokenizer(data)

    else:

        #按字进行编码

        return [tokenizer(review) for review in data]


0.39


In [22]:
print(dataset)

+-------------------------------------+--------+
| raw_words                           | target |
+-------------------------------------+--------+
| 六一出生的？好讽刺…… //@祭春姬...   | 0      |
| 听过一场！笑死了昂，一听茄子脱口... | 1      |
| 说不出话来[泪] //@央广郭亮：//@...  | 0      |
| 疼死我了，一下汗就出来了！扎我一... | 0      |
| 凭啥不让发?!支持! //@臭丫头妈:协... | 0      |
| 回复@PandaraShu:[哈哈][哈哈] //...  | 1      |
| [哈哈] //@清华南都:[吐][吐]//@四... | 1      |
| 所以新片这个造型是向自己第一部电... | 0      |
| 就让爱已成往事吧！我们一起走过[...  | 0      |
| [哈哈] //@日下客:回复@gerald__l...  | 1      |
| 绝对明显  反差！还谈啥素质教育！... | 0      |
| 回复@苏瑾coco:哇！太开心了！[爱...  | 1      |
| 回复@凯文阿公:同意！[鼓掌] //@凯... | 1      |
| 今晚在公司会议室跟@窦赢 用投影踢... | 1      |
| @宁夏广电总台新闻广播 #最美宁夏...  | 1      |
| #爸爸去哪儿威海站# 网友“尴尬美...   | 1      |
| 哪天去尝尝 //@家有懒猫0101:@三宝... | 0      |
| //@咱们一起去旅行:怀念哥哥！[伤...  | 0      |
| 以后都卖切糕，保证发财。比金子都... | 0      |
| 意大利音乐老师们说:"学习音乐本身... | 1      |
| 左边是晶化玻璃？//@?一堂YC: ?在...  | 0      |
| 夜深了，忙碌一天的脚步缓和下来，... | 1      |
| 回复@酸辣汤-说相声的张涛:[哈哈]...  | 1      |
| 旅游，就一句话：一分钱一分货啊！... 

In [23]:
dataset.apply(lambda ins:get_tokenized(ins['raw_words']), new_field_name='words', is_input=True)
print(dataset)

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\ADMINI~1\AppData\Local\Temp\jieba.cache
Loading model cost 2.286 seconds.
Prefix dict has been built successfully.


+---------------------------+--------+---------------------------+
| raw_words                 | target | words                     |
+---------------------------+--------+---------------------------+
| 六一出生的？好讽刺……...   | 0      | ['六一', '出生', '的'...  |
| 听过一场！笑死了昂，一... | 1      | ['听过', '一场', '！'...  |
| 说不出话来[泪] //@央广... | 0      | ['说不出', '话', '来'...  |
| 疼死我了，一下汗就出来... | 0      | ['疼死', '我', '了', ...  |
| 凭啥不让发?!支持! //@...  | 0      | ['凭', '啥', '不让', ...  |
| 回复@PandaraShu:[哈哈...  | 1      | ['回复', '@', 'Pandar...  |
| [哈哈] //@清华南都:[吐... | 1      | ['[', '哈哈', ']', ' ...  |
| 所以新片这个造型是向自... | 0      | ['所以', '新片', '这个... |
| 就让爱已成往事吧！我们... | 0      | ['就让', '爱', '已成'...  |
| [哈哈] //@日下客:回复...  | 1      | ['[', '哈哈', ']', ' ...  |
| 绝对明显  反差！还谈啥... | 0      | ['绝对', '明显', ' ',...  |
| 回复@苏瑾coco:哇！太开... | 1      | ['回复', '@', '苏瑾',...  |
| 回复@凯文阿公:同意！[...  | 1      | ['回复', '@', '凯文',...  |
| 今晚在公司会议室跟@窦...  | 1      | ['今晚', '在', '公司'...  |
| @宁夏广电总台新闻广播...  | 1      | ['@', '宁夏', 

In [24]:
dataset.apply(lambda ins: len(ins['words']) ,new_field_name='seq_len', is_input=True)

print(dataset)

+----------------------+--------+----------------------+---------+
| raw_words            | target | words                | seq_len |
+----------------------+--------+----------------------+---------+
| 六一出生的？好讽...  | 0      | ['六一', '出生',...  | 42      |
| 听过一场！笑死了...  | 1      | ['听过', '一场',...  | 48      |
| 说不出话来[泪] /...  | 0      | ['说不出', '话',...  | 26      |
| 疼死我了，一下汗...  | 0      | ['疼死', '我', '...  | 54      |
| 凭啥不让发?!支持...  | 0      | ['凭', '啥', '不...  | 76      |
| 回复@PandaraShu:...  | 1      | ['回复', '@', 'P...  | 43      |
| [哈哈] //@清华南...  | 1      | ['[', '哈哈', ']...  | 66      |
| 所以新片这个造型...  | 0      | ['所以', '新片',...  | 62      |
| 就让爱已成往事吧...  | 0      | ['就让', '爱', '...  | 114     |
| [哈哈] //@日下客...  | 1      | ['[', '哈哈', ']...  | 59      |
| 绝对明显  反差！...  | 0      | ['绝对', '明显',...  | 61      |
| 回复@苏瑾coco:哇...  | 1      | ['回复', '@', '苏... | 86      |
| 回复@凯文阿公:同...  | 1      | ['回复', '@', '凯... | 43      |
| 今晚在公司会议室...  | 1      | ['今晚', '在', '...  | 31     

In [25]:
dataset.apply(lambda x: int(x['target']), new_field_name='target', is_target=True)
print(dataset)

+----------------------+--------+----------------------+---------+
| raw_words            | target | words                | seq_len |
+----------------------+--------+----------------------+---------+
| 六一出生的？好讽...  | 0      | ['六一', '出生',...  | 42      |
| 听过一场！笑死了...  | 1      | ['听过', '一场',...  | 48      |
| 说不出话来[泪] /...  | 0      | ['说不出', '话',...  | 26      |
| 疼死我了，一下汗...  | 0      | ['疼死', '我', '...  | 54      |
| 凭啥不让发?!支持...  | 0      | ['凭', '啥', '不...  | 76      |
| 回复@PandaraShu:...  | 1      | ['回复', '@', 'P...  | 43      |
| [哈哈] //@清华南...  | 1      | ['[', '哈哈', ']...  | 66      |
| 所以新片这个造型...  | 0      | ['所以', '新片',...  | 62      |
| 就让爱已成往事吧...  | 0      | ['就让', '爱', '...  | 114     |
| [哈哈] //@日下客...  | 1      | ['[', '哈哈', ']...  | 59      |
| 绝对明显  反差！...  | 0      | ['绝对', '明显',...  | 61      |
| 回复@苏瑾coco:哇...  | 1      | ['回复', '@', '苏... | 86      |
| 回复@凯文阿公:同...  | 1      | ['回复', '@', '凯... | 43      |
| 今晚在公司会议室...  | 1      | ['今晚', '在', '...  | 31     

In [26]:
#testset.apply(lambda ins: list(chain.from_iterable(get_tokenized(ins['raw_words']))), new_field_name='words', is_input=True)

testset.apply(lambda ins: get_tokenized(ins['raw_words']), new_field_name='words', is_input=True)

testset.apply(lambda ins: len(ins['words']) ,new_field_name='seq_len',is_input=True)
print(testset)

+---------------------------+---------------------------+---------+
| raw_words                 | words                     | seq_len |
+---------------------------+---------------------------+---------+
| 就是累了，比舒小姐要早... | ['就是', '累', '了', ...  | 82      |
| 今天紫外线强度太强了，... | ['今天', '紫外线', '强... | 20      |
| ~~ //@lichgo://@雪虹坚... | ['~', '~', ' ', '/', ...  | 118     |
| 有一个小姑娘，她有两部... | ['有', '一个', '小姑娘... | 75      |
| 感动[泪][泪]              | ['感动', '[', '泪', '...  | 7       |
| 早起，坐公交，吹冷风。... | ['早起', '，', '坐', ...  | 26      |
| 北京冬季天气偏干燥，及... | ['北京', '冬季', '天气... | 32      |
| 哈哈哈哈[哈哈]//@鹦鹉...  | ['哈哈哈哈', '[', '哈...  | 24      |
| 回复@暗地黑羊:别打人，... | ['回复', '@', '暗地',...  | 108     |
| 还记得小时候看过一种说... | ['还', '记得', '小时候... | 33      |
| 太客气啦啦....么么哒！... | ['太', '客气', '啦', ...  | 20      |
| TVB新片?拜兼?年?[鼓掌...  | ['TVB', '新片', '?', ...  | 11      |
| 跳了么，你们跳了么？/...  | ['跳', '了', '么', '，... | 32      |
| [泪] //@梦都夜话之风之... | ['[', '泪', ']', ' ',...  | 53      |
| 刚接到店家的通知，今年... | ['刚',

In [27]:
###

from fastNLP import Vocabulary

#将DataSet按照ratio的比例拆分，返回两个DataSet

#ratio (float) -- 0<ratio<1, 返回的第一个DataSet拥有 (1-ratio) 这么多数据，第二个DataSet拥有`ratio`这么多数据

train_data, dev_data = dataset.split(0.1, shuffle=False)


In [28]:
print(train_data)

+----------------------+--------+----------------------+---------+
| raw_words            | target | words                | seq_len |
+----------------------+--------+----------------------+---------+
| 打喷嚏，流鼻涕，...  | 0      | ['打喷嚏', '，',...  | 20      |
| 今天去南京为新剧...  | 0      | ['今天', '去', '...  | 97      |
| 路上都有过年的气...  | 0      | ['路上', '都', '...  | 25      |
| 回复@张翡翠:嘿嘿...  | 1      | ['回复', '@', '张... | 95      |
| 国外的一些无节操...  | 1      | ['国外', '的', '...  | 16      |
| 中奖几率会更高吗...  | 1      | ['中奖', '几率',...  | 63      |
| 怎么就知道拍照片...  | 0      | ['怎么', '就', '...  | 14      |
| #豆果年会#超好玩...  | 1      | ['#', '豆果', '年... | 53      |
| //@微博搞笑排行榜... | 1      | ['/', '/', '@', ...  | 23      |
| 这里明明都是高富...  | 1      | ['这里', '明明',...  | 8       |
| [衰]//@爱做饭的疯... | 0      | ['[', '衰', ']',...  | 15      |
| 过度解读！！[悲伤... | 0      | ['过度', '解读',...  | 36      |
| //@百合网: 最后半... | 1      | ['/', '/', '@', ...  | 26      |
| 别再问我为什么今...  | 0      | ['别', '再', '问...  | 53      |
| 感谢

In [29]:
print(len(train_data),len(dev_data),len(testset))

98990 10998 10000


In [30]:
vocab = Vocabulary(min_freq=2).from_dataset(dataset, field_name='words')

vocab.index_dataset(train_data, dev_data, testset, field_name='words', new_field_name='words')

Vocabulary(['六一', '出生', '的', '？', '好']...)

In [31]:
from fastNLP.embeddings import StaticEmbedding,StackEmbedding

fastnlp_embed = StaticEmbedding(vocab, model_dir_or_name='cn-char-fastnlp-100d',min_freq=2)


Found 4000 out of 93812 words in the pre-training embedding.


In [32]:
from fastNLP.models import CNNText

model_CNN = CNNText(fastnlp_embed, num_classes=2,dropout=0.1)

print(model_CNN)

CNNText(
  (embed): Embedding(
    (embed): StaticEmbedding(
      (dropout_layer): Dropout(p=0)
      (embedding): Embedding(93812, 100, padding_idx=0)
    )
    (dropout): Dropout(p=0.0)
  )
  (conv_pool): ConvMaxpool(
    (convs): ModuleList(
      (0): Conv1d(100, 30, kernel_size=(1,), stride=(1,), bias=False)
      (1): Conv1d(100, 40, kernel_size=(3,), stride=(1,), padding=(1,), bias=False)
      (2): Conv1d(100, 50, kernel_size=(5,), stride=(1,), padding=(2,), bias=False)
    )
  )
  (dropout): Dropout(p=0.1)
  (fc): Linear(in_features=120, out_features=2, bias=True)
)


In [ ]:
from fastNLP import Trainer, CrossEntropyLoss, AccuracyMetric,BCELoss

trainer_CNN = Trainer(model=model_CNN, train_data=train_data, dev_data=dev_data,loss=CrossEntropyLoss(), metrics=AccuracyMetric())

trainer_CNN.train()

input fields after batch(if batch size is 2):
	words: (1)type:torch.Tensor (2)dtype:torch.int64, (3)shape:torch.Size([2, 97]) 
	seq_len: (1)type:torch.Tensor (2)dtype:torch.int64, (3)shape:torch.Size([2]) 
target fields after batch(if batch size is 2):
	target: (1)type:torch.Tensor (2)dtype:torch.int64, (3)shape:torch.Size([2]) 

training epochs started 2020-06-18-18-00-50-035273


Evaluate data in 14.29 seconds!
Evaluation on dev at Epoch 1/10. Step:3094/30940: 
AccuracyMetric: acc=0.985452



Evaluate data in 13.89 seconds!
Evaluation on dev at Epoch 2/10. Step:6188/30940: 
AccuracyMetric: acc=0.959083



Evaluate data in 14.57 seconds!
Evaluation on dev at Epoch 3/10. Step:9282/30940: 
AccuracyMetric: acc=0.985543



In [ ]:
demo=[]

In [ ]:
import pandas as pd

import torch

def batch_predict(model,data):
#     submission=pd.DataFrame(columns=['Prediction'])
#    submission = pd.DataFrame(columns=['ID','Prediction'])
    demo1=[]
    for i in range(len(data)):
    #for i in range(5):
#         print(data.words[i])
        tensor = torch.tensor(data.words[i])
        pred = model.predict(tensor.view(1,-1))
#         print(pred)
        prob = pred['pred'].numpy()[0]
#         print("pred:%.2f"%(prob))
#         print('='*50)
#         print(type(prob))
#         s2 = pd.Series([float(prob)], index=['Prediction'])
        demo1.append(prob)
#         print(prob)
# #         print(s2)
#         submission = submission.append(s2, ignore_index=True)
#         submission['Prediction'] = submission.Prediction .astype(int)
#         submission['']
#         submission['Prediction'] = submission.Prediction.astype(float) 
    return demo1

In [ ]:
demo=batch_predict(model_CNN,testset)

In [ ]:
print(len(demo))

In [ ]:
from sklearn.metrics import accuracy_score

print(accuracy_score(testlist,demo))